config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :photos, only: [:index, :new, :create, :show, :destroy] do
    resources :comments, only: [:new, :create, :destroy]
  end

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :image, :caption, presence: true
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # dependent: :destroy will destroy the associated records if a user is destroyed
  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.create(comment_params)
    @comment.user_id = current_user
    redirect_to photo_path(@photo)
  end

  def destroy
    @photo = Photo.find(params[:photo_id])
    @comment = @photo.comments.find(params[:id])
    @comment.destroy
    redirect_to photo_path(@photo)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.where(user_id: current_user.id).order(created_at: :desc)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.build photo_params
    if @photo.save
      redirect_to @photo
    else
      render 'new'
    end
  end

  def show
    @photo = Photo.find params[:id]
  end

  def destroy
    @photo = Photo.find params[:id]
    if @photo.user = current_user
      @photo.destroy
      redirect_to photos_path
      flash.notice = "Photo successfully deleted"
    else
      redirect_to photos_path
      flash.alert = "Invalid Permissions"
    end
  end

  private
    def photo_params
      params.require(:photo).permit(:public, :caption, :image)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @photos = Photo.where(public: true).order(created_at: :desc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="comments">
	<p>
	  <strong><%= comment.commenter %>: </strong><%= comment.body %>
	</p>
</div>
<p>
  <%= link_to 'delete comment', [comment.photo, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@photo, @photo.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter, "bru: " %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body, "comment: " %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %> 
  </p>
<% end %>

app/views/layouts/_alerts.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_nav.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BruGram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= render 'layouts/nav' %>

	<%= render 'layouts/alerts' %>
	<%= yield %>
</div>

</body>
</html>

app/views/photos/_form.html.erb
<% if @photo.errors.present? %>
  <% @photo.errors.full_messages.each do |msg| %>
    <p style="color: red"><b><%= msg %></b></p>
  <% end %>
<% end %>

<%= form_for @photo, :html => { :multipart => true } do |f| %>
  <p>
    <%= f.label :image, "photo URL" %><br>
    <%= f.text_field :image %>
  </p>
  <p>
    <%= f.label :caption %><br>
    <%= f.text_field :caption %>
  </p>
  <p>
    <%= f.label :public, "public?" %><br>
    <%= f.check_box :public %> Yes
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/photos/index.html.erb
<h1>showin all ur photos</h1>
<!-- for some reason i need to do this or else it prints anyway -->
<% if @photos.first %>
  <% @photos.each do |photo| %>
      <img src="<%= photo.image %>">
    <p><%= link_to photo.caption, photo_path(photo) %></p>
  <% end %>
<% else %>
  <p>u haven't posted any photos yet</p>
<% end %>
<br>
<br>
<%= link_to "post a new photo", new_photo_path %>

app/views/photos/new.html.erb
<h1>postin a new photo</h1>
<p><b>instructions:</b> make sure to include the full URL.  checking "yes" for public means anyone can see your photo.  leaving the box unchecked means only brugram members will be able to see it.</p>

<%= render 'form' %>

app/views/photos/show.html.erb
<h1>showin a photo</h1>
<img src="<%= @photo.image %>">
<p><%= @photo.caption %></p>
<%= link_to "delete", photo_path(@photo), method: :delete, data: { confirm: 'Are you sure?' } %>
<h2>Comments</h2>
<%= render @photo.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to "back to home", photos_path %>

app/views/welcome/index.html.erb
<h1>Showing all public photos</h1>

<% if @photos.first %>
  <% @photos.each do |photo| %>
    <img src="<%= photo.image %>">
    <p><%= link_to photo.caption, photo_path(photo)%></p>
  <% end %>
<% else %>
  <p>There are no photos yet.</p>
<% end %>

<%= link_to "your personal photos", photos_path %>